### ISSUE TITLE
DNS-01 challenge for wildcard certificates?

### ISSUE THREAD

**Issue by deyanp** [Arnavion/acme-azure-function#1]
First, great work!! Very useful for me as I am using F# for all the microservices etc. 

I see that you have implemented the HTTP-01 challenge only, but as I want to issue wildcard certificate I would have to use DNS-01 ... Have you done anything in that direction? I guess I have to just replace the part where you put a blob on the storage account with some API calls to Azure DNS (in my case DNS is Azure hosted as well) ..

**Comment by Arnavion** [comment]
The registrar for the domain that I use this for doesn't have a programmable API, so I can't use a DNS-01 challenge myself.

Yes, `RenewKeyVaultCertificateOrchestratorInstance` uses `SetChallengeBlobInStorageAccount` once to create a challenge blob in the storage account, then again to delete it. You'd replace that with creating the TXT record in Azure DNS, then deleting it.

**Comment by Arnavion** [comment]
>The registrar for the domain that I use this for doesn't have a programmable API, so I can't use a DNS-01 challenge myself.

Reading HN today reminded me that NS records exist, so it's probably possible to have an Azure DNS server just for the `_acme-challenge` subdomain's records.

If so, I might switch to that for my own domain too, so let's reopen this.
